FROM node:18-alphine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


FROM node:1i8-alphine

WORKDIR /app

COPY --from=builder /app .


EXPOSE 3000

CMD ["npm", "start"]